#!/bin/bash
exec < /dev/tty

# Get the current branch name
branch_name=$(git branch | grep "*" | sed "s/\* //")

# Get the name of the branch that was just merged
reflog_message=$(git reflog -1)
merged_branch_name=$(echo $reflog_message | cut -d" " -f 4 | sed "s/://")

# if the merged branch was master - don't do anything
if [[ $merged_branch_name = "master" ]]; then
    exit 0
fi

# Begin output
echo " "
echo "You've just merged the branch \"$merged_branch_name\" into \"$branch_name\". "

if [[$merged_branch_name = 'dev'] || [$merged_branch_name = 'Fast-forward'] ]  && [ $branch_name = 'main' ]
then
    echo "Both conditions are true"
	grep -rl --exclude-dir=.git --exclude-dir=.githooks 'subdomains/ote' . | xargs sed -i 's~subdomains\/ote~httpdocs~g';
else
    echo "No bash executed"
fi
